In [ ]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.19.0


In [ ]:
# Scalar (0D tensor)
scalar = tf.constant(10)
print("Scalar:", scalar)
print("Shape:", scalar.shape)
print("Rank (dimension):", tf.rank(scalar).numpy())




Scalar: tf.Tensor(10, shape=(), dtype=int32)
Shape: ()
Rank (dimension): 0


In [ ]:
# Vector (1D tensor)
vector = tf.constant([10, 20, 30])
print("\nVector:", vector)
print("Shape:", vector.shape)
print("Rank:", tf.rank(vector).numpy())


Vector: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Shape: (3,)
Rank: 1


In [ ]:
# Matrix (2D tensor)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:\n", matrix)
print("Shape:", matrix.shape)
print("Rank:", tf.rank(matrix).numpy())



Matrix:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Rank: 2


In [ ]:
# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape)
print("Rank:", tf.rank(tensor_3d).numpy())


3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)
Rank: 3


In [ ]:
a = tf.constant([1, 2, 3], dtype=tf.int32)
b = tf.constant([4, 5, 6], dtype=tf.int32)

# Element-wise operations
print("Addition:", tf.add(a, b).numpy())
print("Subtraction:", tf.subtract(a, b).numpy())
print("Multiplication:", tf.multiply(a, b).numpy())
print("Division:", tf.divide(b, a).numpy())


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


In [ ]:
# Dot product
dot = tf.tensordot(a, b, axes=1)
print("Dot Product:", dot.numpy())

# Matrix multiplication
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[5, 6], [7, 8]])
matmul = tf.matmul(mat1, mat2)
print("Matrix Multiplication:\n", matmul.numpy())


Dot Product: 32
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [ ]:
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])

# Reshape (3x2 → 2x3)
reshaped = tf.reshape(matrix, [2, 3])
print("Reshaped:\n", reshaped.numpy())

# Transpose
transposed = tf.transpose(matrix)
print("\nTransposed:\n", transposed.numpy())


Reshaped:
 [[1 2 3]
 [4 5 6]]

Transposed:
 [[1 3 5]
 [2 4 6]]


In [ ]:
float_tensor = tf.constant([1.7, 2.3, 3.9], dtype=tf.float32)

# Cast float to int
int_tensor = tf.cast(float_tensor, dtype=tf.int32)

print("Original:", float_tensor.numpy())
print("Casted:", int_tensor.numpy())


Original: [1.7 2.3 3.9]
Casted: [1 2 3]


In [ ]:
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

print("Sum:", tf.reduce_sum(matrix).numpy())
print("Mean:", tf.reduce_mean(matrix).numpy())
print("Max:", tf.reduce_max(matrix).numpy())
print("Min:", tf.reduce_min(matrix).numpy())


Sum: 10.0
Mean: 2.5
Max: 4.0
Min: 1.0


In [ ]:
# Define a variable
var = tf.Variable([1, 2, 3], dtype=tf.int32)
print("Before:", var.numpy())

# Assign new values
var.assign([4, 5, 6])
print("After assign:", var.numpy())

# Add to variable
var.assign_add([1, 1, 1])
print("After assign_add:", var.numpy())

# Subtract from variable
var.assign_sub([2, 2, 2])
print("After assign_sub:", var.numpy())


Before: [1 2 3]
After assign: [4 5 6]
After assign_add: [5 6 7]
After assign_sub: [3 4 5]
